server:
  port: 8081
spring:
  application:
    name: account-service
  config:
    import:
      - optional:configserver:http://localhost:8071/
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/